Adiciona uma nota
Isaac-alencar/react-challenge-notes pull request #5
Opened 2024-04-23 19:16 UTC by andre-fsantos

2024-04-23 19:21 UTC, Isaac-alencar commented on src/Components/Layout.jsx
> +            if(response.id !== undefined) showToast({ message: 'Nota adicionada!', bgColor: '#a7f5a7' });
Ao invés de passar o brackground color, que é um detalhe de implementação, seria melhor passar algo como

```js
showToast({ message: "...", type: "success" })
```

isso esconde a lógica por trás do toast e o componente que usa ele só saberá se o toast é pra sucesso, erro, aviso, etc...

2024-04-23 19:23 UTC, Isaac-alencar commented on src/Components/Layout.jsx
> +    }
isso é um detalhe de implementação do toast, quem consome o componente não pode saber como essas coisas são feitas. uma dica: implementa isso no componente e usa as variaveis como `isToastVisible` como props, aí tu passa essas props quando for usar ele

- move a lógica pro toast;
- as variaveis serão recebidas como propriedades (props)
- o estado de aberto ou feachdo fica no componente que esta usando ele

2024-04-23 19:24 UTC, Isaac-alencar commented on src/Components/Layout.jsx
> +        };
isso não é necessário para navegação com o teclado, existe uma forma mais simples: a tag `<form>` e usar os elementos apropriados dentro do form

2024-04-23 19:25 UTC, Isaac-alencar commented on src/Components/Layout.jsx
> +    const [dataToast, setDataToast] = useState({});
isso não faz parte desse componente, deve ser movido para o toast

2024-04-23 20:03 UTC, Isaac-alencar commented on src/Components/Layout.jsx
> +            if(response.id !== undefined) showToast({ message: 'Nota adicionada!', bgColor: '#a7f5a7' });
ler sobre falsy  values. essa comparação pode ser resumida em: 

```js
if (!response.id) {
//...
}
```

2024-04-24 12:31 UTC, andre-fsantos commented on src/Components/Layout.jsx
> +            if(response.id !== undefined) showToast({ message: 'Nota adicionada!', bgColor: '#a7f5a7' });
`response.id` será uma _string_ não vazia (truthy) ou _undefined_ (falsy). Logo, a implementação não deveria ter `!`. Correto? Assim: `if(response.id)`

2024-04-24 13:51 UTC, andre-fsantos commented on src/Components/Layout.jsx
> +            fecthGetNotes();
Envia para mim algum artigo em que incentive o uso do `window.location.reload()` pelo menos nesse caso específico. Pesquisei e só encontrei afirmações contrárias. Além disso, não entendo como o _toast_ poderia ser mantido, já que a página inteira é recarregada.

2024-04-24 15:38 UTC, Isaac-alencar commented on src/Components/Toast.jsx
> +import { useEffect } from 'react';
sei que a gente discutiu sobre isso ontem, não conseguirmos implementar juntos o toast. essa implementação, funcionou, vc testou? só curiosidade mesmo

2024-04-24 15:49 UTC, Isaac-alencar commented on src/Components/Layout.jsx
> +            fecthGetNotes();
na verdade, o que podemos fazer é algo até mais elegante, etive pensando nisso de ontem pra hoje. não será necessário nem recarregar a página, nem refazer o fetch.

```js
const addNote = async () => {
  try {
    const response = await saveNote({ title, description });
    if (response.id) {
      setIsToastVisible(true);
      setMessageToast("Nota adicionada!");
      setToastType("success");

      /** essa linha vai modificar o valor atual de notes sem precisar recarregar 
           ou refazer o fetch. Essa sintaxe aqui de setNotes é bem comum e 
           estamos modificando de maneira segura o valor desse array */
           setNotes((oldValue) => [...oldValue, { title, description }]);
    }

    setTitle("");
    setDescription("");
  } catch (error) {
    // ....
  }
};
```

outra coisa, o toast em sí não é necessário. isso foi uma implementação sua 🤷🏻‍♂️

2024-04-24 15:51 UTC, Isaac-alencar commented on src/Components/Layout.jsx
> +            fecthGetNotes();
> Envia para mim algum artigo em que incentive o uso do `window.location.reload()` pelo menos nesse caso específico. Pesquisei e só encontrei afirmações contrárias. Além disso, não entendo como o _toast_ poderia ser mantido, já que a página inteira é recarregada.

então, nesse caso não faz muita diferença (como discutimos). porém, dependendo da situação o reload na página é melhor, fazer requisições http sempre terá um custo para o usuário final, é sempre necessśario otimizar e evitar fazê-las sem necessidade

2024-04-24 15:52 UTC, Isaac-alencar requested changes

2024-04-24 15:52 UTC, Isaac-alencar commented on src/Components/Layout.jsx
> +                <form onSubmit={e => e.preventDefault()}>
👍🏻

2024-04-24 17:07 UTC, andre-fsantos commented on src/Components/Toast.jsx
> +import { useEffect } from 'react';
Sim, funcionou.

2024-04-24 20:24 UTC, Isaac-alencar commented on src/Components/Layout.jsx
> +                    event => {
nada de errado, mas particularmente não gosto. então fica só a dica msm: se essa função passar de duas linhas, considera mover ela pra fora, então como não passou ta de boas, mas fica a dica

2024-04-24 20:24 UTC, Isaac-alencar approved these changes

2024-04-24 20:25 UTC, merged